name: 'publish'

on:
  push:
    branches:
      - '*'
    tags:
      - '*'

jobs:  
  build:
    name: 'Build and publish'
    runs-on: ubuntu-latest
    steps:
    
      - name: 'Build checkout'
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/pixilib/gaelo-pathology-processing
          tags: |
            type=ref,event=tag
            latest
            
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to github registery
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: 'salimkanoun'
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: setup git config
        run: |
          git config user.name "Salim Kanoun"
          git config user.email "salim.kanoun@gmail.com"

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          pull: true
          secrets: |
            "github_token=${{ secrets.TOKEN }}"
          tags: ${{ steps.meta.outputs.tags }}
