name: 'tests'

on:
  push:
    branches:
      - '*'

jobs:  
  build:
    name: 'Tests'
    runs-on: ubuntu-latest
    steps:
    
      - name: 'Build checkout'
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: login to github registery
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: 'salimkanoun'
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: setup git config
        run: |
          git config user.name "Salim Kanoun"
          git config user.email "salim.kanoun@gmail.com"

      - name: add libjpeg turbo repository
        run: |
          sudo wget -q -O- https://packagecloud.io/dcommander/libjpeg-turbo/gpgkey | \
          gpg --dearmor >/etc/apt/trusted.gpg.d/libjpeg-turbo.gpg && sudo apt update

      - name: install libjpeg turbo
        run: |
          sudo apt-get install libjpeg-turbo

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: install dependancies
        run: pip install -r requirements.txt
        working-directory: ./src

      - name: tests
        run: python manage.py test
        working-directory: ./src
